class ExceptionEx{
static void main(String[] args){
try{
def arr=new int[3];
arr[5]=5;
}
catch()
}
}